apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcvolume
  namespace: admin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs-heketi
  volumeMode: Filesystem
