apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: tfcluster-client
    job-name: tfcluster-client
    clustername: tfcluster
  name: tfcluster-client
  namespace: admin
spec:
  template:
    metadata:
      labels:
        app: tfcluster-client
        job-name: tfcluster-client
        clustername: tfcluster
      name: tfcluster-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cputype
                operator: In
                values:
                - intel-xeon-e5-2620-v4
              - key: pooltype
                operator: In
                values:
                - shared
      containers:
      - env:
        - name: TRAIN_ENGINE
          value: tensorflow
        - name: CLUSTER_NAME
          value: tfcluster
        - name: CLUSTER_SPEC
          value: ps|tfcluster-ps-0.tfcluster-ps:2222;tfcluster-ps-1.tfcluster-ps:2222,worker|tfcluster-worker-0.tfcluster-worker:2222;tfcluster-worker-1.tfcluster-worker:2222;tfcluster-worker-2.tfcluster-worker:2222
        - name: RESOURCE_TYPE
          value: client
        image: tensorflow-cpu:1.12.0
        imagePullPolicy: IfNotPresent
        name: tfcluster-client
        ports:
        - containerPort: 8888
          name: client-port
          protocol: TCP
        - containerPort: 22
          name: ssh-port
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /root/tensorflow
          name: tfcluster-data-0
      volumes:
      - name: tfcluster-data-0
        persistentVolumeClaim:
          claimName: pvcvolume
