apiVersion: v1
kind: Service
metadata:
  labels:
    app: tfcluster-client
    clustername: tfcluster
  name: tfcluster-client
  namespace: admin
spec:
  ports:
  - name: jupyter
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: tfcluster-client
  type: NodePort
