apiVersion: v1
kind: Service
metadata:
  labels:
    app: tfcluster-ps
    clustername: tfcluster
  name: tfcluster-ps
  namespace: admin
spec:
  ports:
  - name: tfport
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: tfcluster-ps
  type: ClusterIP
