apiVersion: v1
kind: Service
metadata:
  labels:
    app: tfcluster-tfboard
    clustername: tfcluster
  name: tfcluster-tfboard
  namespace: admin
spec:
  ports:
  - port: 6006
    protocol: TCP
    targetPort: 6006
  selector:
    app: tfcluster-tfboard
  type: NodePort
